<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US"><head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=8">
<title>Mutual of Omaha Life Insurance, Disability Insurance &amp; More</title>
<meta name="description" content="Mutual of Omaha is a leading provider of life insurance, Medicare supplement insurance, disability insurance products and annuities. Visit today.">
<meta name="keywords" content="life insurance, life insurance company">
<script src="js/jquery-1.11.1.js"></script>
<script src="bootstrap3/js/bootstrap.js"></script>
<script src="bootstrap3/js/bootstrap.min.js"></script>
<script language="Javascript" src="js/jquery-2.1.1.js"></script>
<link rel="stylesheet" href="js/jqm/jquery.mobile-1.4.4.min.css">
<script src="js/jqm/_assets/js/jquery.js"></script>
<script src="js/jqm/_assets/js/index.js"></script>
<script src="js/jqm/jquery.mobile-1.4.4.min.js"></script>
<link rel="stylesheet" type="text/css" href="css/site.css">
<link rel="stylesheet" type="text/css" href="bootstrap3/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="bootstrap3/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="bootstrap3/css/bootstrap-theme.css">
<link rel="stylesheet" type="text/css" href="bootstrap3/css/bootstrap-theme.min.css">

<body id="homepage" >
<div id="mmenu" data-role="header" class="jqm-header">
	<h2><a title="Mutual of Omaha"><img src="images/pixel-m.png" width="100%" height="auto" alt="Mutual of Omaha"></a></h2>
	<a href="#" class="jqm-navmenu-link ui-btn ui-btn-icon-notext ui-corner-all ui-icon-bars ui-nodisc-icon ui-alt-icon ui-btn-left">Menu</a>
</div>

<div id="wrapper">
<div id="header">
	<div id="logo">
		<img src="images/pixel.gif" width="100%" height="auto" alt="" title="Mutual of Omaha">
	</div> 

	<a href="#">
	<div id="utilities">
		<img src="images/call.png" width="100%" height="auto" alt="" title="Mutual of Omaha">
	</div>
	</a>
</div> 



<div id="content-wrapper">
	<div id="nav-html" style="color:#fff;background-color:#093157;">
		<ul class="nav nav-tabs">
			<li><a href='insurance.php'>What is Medical Supplement Insurance</a></li>
			<li><a href='options.php'>Medicare Supplement Plan Options</a></li>
			<li><a href='faqs.php'>FAQs</a></li>
			<li><a href='#'>Request a Free Quote Today!</a></li>
		</ul>
	</div>
	<div id="orange">
			<div width="100%">
			<img src="images/m-ad.png" alt="" title="Mutual of Omaha" width="100%" style="position: relative; ">		
			<h2 align="center" style="color:#FFFFFF;"><b>Get Started!</b></h2>
			<h4 align="center" style="color:#FFFFFF;">Request your no-obligation quote today!</h4>
			</div>
		</div>
<div id="banner">
	
	<div id="ad-carousel">
		<div id="ads">
			<div class="ad">
				<div class="ad-image">
					<img src="images/ad.png" alt="" title="Mutual of Omaha" border="0" width="100%" style="position: relative; top: 5px; left: 5px; right: 5px;">			
					<div id="ad-info" style="position: relative; bottom: 5px; left: 5px; right: 5px;">
						<p align="left"><h4>Medical Supplement Insurance</h4></p>
						<p>Complete coverage for individuals ages 65 and over from Mutual of Omaha. We help cover healthcare cost that traditional 
						Medicare does not. Allow our licensed health insurance agents find the right Plan <a href="#">for you. Get your FREE quote now!</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="login">
		<div class="panel panel-warning">
			<div class="panel-heading">
				<h3 class="panel-title"><b>Get Started!</b></h3>
				<p>Request your no-obligation quote today!</p>
			</div>
			<div class="panel-body">
				<p align="center">It's easy to get started. Simply answer a few questions and we'll provide you with a free, 
				no obligation quote.</p>
				<form role="form" method="POST" action="newdeals/create">
				<p align="center">	
					<div class="selDiv"  align="center">
					<select id="selected_state" class="opts">
					<?php foreach($this->states as $state) : ?>
						<option value="<?php echo $this->escape($state->id);?>"><?php echo $this->escape($state->name);?></option>
					<?php $arr[$this->escape($state->id)]=$this->escape($state->name); endforeach; ?>
					</select>
					</div>
				</p>
				<p align="center">
					<button type="submit" class="btn btn-warning">Get Started ></button>
				</p>
				</form>
			</div>
		</div>
	</div>

	
</div>

			<div id="mform"class="panel-body" style="background-color:#FFFFFF;">
				<p align="center">It's easy to get started. Simply answer a few questions and we'll provide you with a FREE, 
				no obligation quote.</p>
				<form role="form" method="POST" action="newdeals/create">
				<p align="center">
					<div class="selDiv"  align="center">
					<select id="selected_state" class="opts">
					<?php foreach($this->states as $state) : ?>
						<option value="<?php echo $this->escape($state->id);?>"><?php echo $this->escape($state->name);?></option>
					<?php endforeach; ?>
					</select>
					</div>
				</p>
				<p align="center">
					<button type="submit" class="btn btn-warning" style="color:#FFFFFF;">Get Started!    ></button>
				</p>
				</form>				
			</div>

<div id="extras">
	<div id="quick-links">
		<h2>The Benefits of Owning a Medicare Supplement Insurance Policy</h2>
        <p>With all the choices you have for your health care coverage, It's important to understand how each one works, its benefits and you share 
		of the cost. Here's a brief look at how Medicare supplement insurance differs from other coverage , Including Medicare Advantage Plans.
        </p>
		<ul>
			<li>Low Out-of-Pockets Cost</li>
			<li>Keep Your Doctors and Hospitals who accept Medicare</li>
			<li>Coverage is Guaranteed Renewable</li>
		</ul>
		<p>
		<a href="policy.php">Learn More</a>
		</p>
	</div>
	<div id="quick-links-right">
		<h2>Medicare Supplement Insurance Basics</h2>
        <p>Original Medicare covers many health care services and supplies, but there are many costs it doesn't cover. A medigap policy is health insurance
		sold by private insurance companies to fill gaps in Original Medicare coverage.</p>
		<p>
		<a href="insurance.php">> Learn More</a>
		</p>
	</div>
</div>	

<div id="mextras">
		<div>
			<div class="panel-body" style="background-color:#093157;">
				<p align="center" style="color:#FFFFFF"><b>Medical Supplement Insurance</b></p>
							<p align="center" style="color:#FFFFFF">Complete coverage for individuals ages 65 and over from Mutual of Omaha. We help cover healthcare cost that traditional 
							Medicare does not. Allow our licensed health insurance agents find the right Plan for you. Get your FREE quote now!</p>
				<p align="center">
					<button type="submit" class="btn btn-warning" style="color:#FFFFFF;">Get your FREE quote now!</button>
				</p>				
			</div>
		</div>
		<div>
			<div style="background-color:#FFFFFF; padding: 10px;">
				<p><b>The Benefits of Owning a Medicare Supplement Insurance Policy</b></p>
				<p>With all the choices you have for your health care coverage, It's important to understand how each one works, its benefits and you share 
				of the cost. Here's a brief look at how Medicare supplement insurance differs from other coverage , Including Medicare Advantage Plans.
				</p>
				<ul data-role="listview" data-inset="true">
					<li>Low Out-of-Pockets Cost</li>
					<li>Keep Your Doctors and Hospitals who accept Medicare</li>
					<li>Coverage is Guaranteed Renewable</li>
				</ul>
				<p align="center">
					<a href="policy.php"><button type="submit" class="btn btn-default" style="color:#000000;">Learn More</button></a>
				</p>				
			</div>
		</div>
		<div>
			<div id="orange" class="panel-body">
				<h4 align="center" style="color:#FFF"><b>Medicare Supplement Insurance Basics</b></h4>
				<p align="center" style="color:#FFF">Medicare Supplement Insurance Basics Original Medicare covers many health care services and supplies, but there are many costs it doesn't cover. A medigap policy is health insurance
				sold by private insurance companies to fill gaps in Original Medicare coverage.</p>
				<p>
				<p align="center">
					<a href="insurance.php"><button type="submit" class="btn btn-default" style="color:#F3930E;">Learn More</button></a>
				</p>
			</div>
		</div>
</div>


</div>

<div id="mfooter">
	<a href="about.php"><div class="item">About Us</div>
	<a href="price.php"><div class="item">Pricing Options</div>
	<a href="legal/privacy.php"><div class="item">Privacy Policy</div>
	<a href="legal/terms.php"><div class="item">Terms of Use</div>
	<a href="#"><div class="item">Site Map</div>
</div>

<div id="wfooter">
<ul class="sitemap_nav">
	<li id="sitemap_about_nav"><a href="about.php">About Us</a></li>
	<li id="sitemap_pricing_options_nav"><a href="price.php">Pricing Options</a></li>
</ul>
</div>
<div id="footer">
	<div id="wfooter2">
	</br>
	</br>
	<ul class="links">
		<li><a href="legal/privacy.php">Privacy Policy</a></li>
		<li><a href="legal/terms.php">Terms of Use</a></li>
		<li><a href="#">Site Map</a></li>
	</ul>
   	</div>
	<p class="copyright"><img id="sec-image" src="images/secure-site.png" alt="" title="Mutual of Omaha" border="0"></p>
    </br>
    </br>
    </br>
	<p>© 2013 Mutual of Omaha Insurance Company. All rights reserved.</p>
	<p>Powered by TZ Insurance Solutions LLC.</p>
	</br>
	<p>This is a solicitation of insuranced and licensed agent may contact you by telephone to provide additional information. Not connected with endorsed by U.S. government or the Federal Medicare program.</p>
	</br>
	<p>AFN45725</p>

</div>
</div>

</body>
